// Steps for the standalone one-page video brief for a hotel/resort
// (база отдыха). Deliberately separate from STEPS_BY_VARIANT in brief.ts —
// that system drives the multi-screen wizard (intro/page1/page2/review),
// while this brief is a single flat page with one "Отправить" button, per
// Egor's request to keep it as simple as possible for a client to fill in
// two minutes and send.
import type { BriefStep } from "@/lib/brief";

export const HOTEL_VIDEO_STEPS: BriefStep[] = [
  {
    id: "company",
    page: 1,
    scene: 1,
    type: "text",
    title: "Название базы отдыха / отеля",
    placeholder: "Например: База отдыха «Сосновый бор»",
    required: true,
  },
  {
    id: "contact",
    page: 1,
    scene: 1,
    type: "contact",
    title: "Как с вами связаться?",
    help: "Email обязателен, телефон — по желанию.",
    required: true,
  },
  {
    id: "locations",
    page: 1,
    scene: 1,
    type: "text",
    title: "Сколько локаций снимаем?",
    help: "Номера, ресепшн, территория, бассейн, баня и т.д.",
    placeholder: "Например: 5 локаций — ресепшн, 2 типа номеров, территория, зона у воды",
    required: true,
  },
  {
    id: "drone",
    page: 1,
    scene: 1,
    type: "choice",
    title: "Нужна аэросъёмка дроном?",
    options: ["Да", "Нет", "Обсудим на созвоне"],
    required: true,
  },
  {
    id: "actors",
    page: 1,
    scene: 1,
    type: "choice",
    title: "Нужны актёры или модели в кадре?",
    options: ["Да, нужны актёры", "Только сотрудники и гости", "Без людей в кадре"],
    required: true,
  },
  {
    id: "format",
    page: 1,
    scene: 1,
    type: "chips",
    title: "Какой формат ролика нужен?",
    help: "Можно выбрать несколько вариантов.",
    options: [
      "Имиджевое видео",
      "Реклама",
      "Контент для соцсетей",
      "Промо для букинга / OTA",
      "Другое",
    ],
    required: true,
  },
  {
    id: "duration",
    page: 1,
    scene: 1,
    type: "choice",
    title: "Какой хронометраж нужен?",
    options: ["До 30 секунд", "30–60 секунд", "1–3 минуты", "3+ минуты", "Пока не знаю"],
    required: true,
  },
  {
    id: "references",
    page: 1,
    scene: 1,
    type: "textarea",
    title: "Есть ролики, которые нравятся по стилю?",
    help: "Ссылки на YouTube, Reels — по одной на строку.",
    placeholder: "https://…",
    required: false,
  },
  {
    id: "budget",
    page: 1,
    scene: 1,
    type: "choice",
    title: "Какой бюджет закладываете?",
    options: [
      "До 150 000 ₽",
      "150 000–400 000 ₽",
      "400 000–800 000 ₽",
      "800 000 ₽ и выше",
      "Обсудим на созвоне",
    ],
    required: true,
  },
  {
    id: "deadline",
    page: 1,
    scene: 1,
    type: "date",
    title: "К какой дате нужен готовый ролик?",
    help: "Ориентировочно — точный план обсудим на созвоне.",
    required: false,
  },
];
